name: Build and push "dev" images

on:
  workflow_dispatch:
  schedule:
    - cron: '0 14 * * MON'

jobs:
  build-and-push:
    name: Build and push
    if: "github.ref == 'refs/heads/main'"
    strategy:
      matrix:
        page: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
        page-total: [10]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - name: Free more space
      id: free_space
      run: |
        set -e
        # Ensure enough space is available for build
        sudo apt-get autoremove -y
        sudo apt-get clean -y
        sudo rm -rf /usr/share/dotnet

    - name: Checkout
      id: checkout
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push dev tags
      id: build_and_push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_PASS: ${{ secrets.DOCKERHUB_TOKEN }}
        REGISTRY: ${{ secrets.REGISTRY }}
        REGISTRY_BASE_PATH: ${{ secrets.REGISTRY_BASE_PATH }}
        STUB_REGISTRY: ${{ secrets.STUB_REGISTRY }}
        STUB_REGISTRY_BASE_PATH: ${{ secrets.STUB_REGISTRY_BASE_PATH }}
      run: |
        set -e

        # Docker login
        docker login -u $DOCKER_USER -p $DOCKER_PASS

        # Build and push dev images
        yarn install
        npm install -g @devcontainers/cli
        GIT_BRANCH=$(echo "${{ github.ref }}" | grep -oP 'refs/(heads|tags)/\K(.+)')
        if [ "$GIT_BRANCH" == "" ]; then
            GIT_BRANCH=main
        fi
        build/vscdc push  --page ${{ matrix.page }} \
                          --pageTotal ${{ matrix.page-total }} \
                          --release $GIT_BRANCH \
                          --github-repo ${{ github.repository }} \
                          --registry "$REGISTRY" \
                          --registry-path "$REGISTRY_BASE_PATH" \
                          --stub-registry "$STUB_REGISTRY" \
                          --stub-registry-path "$STUB_REGISTRY_BASE_PATH"

  image-info:
    name: Trigger info extraction
    needs: [build-and-push]
    uses: dbarjs/devcontainer-images/.github/workflows/version-history.yml@main
    with:
      release: "${{ github.ref }}"
      cg: "true"
      push: "true"
      overwrite: "true"
    secrets: inherit
